"""create case_analysis table

Revision ID: b739d8630437
Revises: 
Create Date: 2026-01-28 00:13:22.162675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b739d8630437'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('source_hash', sa.Text(), nullable=False),
    sa.Column('analysis_version', sa.Text(), nullable=False),
    sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'source_hash', 'analysis_version', name='uq_case_analysis_case_hash_version')
    )
    op.create_index(op.f('ix_case_analysis_case_id'), 'case_analysis', ['case_id'], unique=False)
    op.create_index("ix_case_analysis_source_hash", "case_analysis", ["source_hash"])
    op.create_index("ix_case_analysis_case_id_created_at", "case_analysis", ["case_id", "created_at"])

    op.alter_column('case_structured', 'normalized_data',
               type_= postgresql.JSONB(),
               postgresql_using="normalized_data::jsonb",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_structured', 'normalized_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_case_analysis_case_id'), table_name='case_analysis')
    op.drop_table('case_analysis')
    # ### end Alembic commands ###
